// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/consignment/consignment.proto

package consignment

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Consignment struct {
	Id                   string       `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Description          string       `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Weight               int32        `protobuf:"varint,3,opt,name=weight,proto3" json:"weight,omitempty"`
	Containers           []*Container `protobuf:"bytes,4,rep,name=containers,proto3" json:"containers,omitempty"`
	VesselId             string       `protobuf:"bytes,5,opt,name=vessel_id,json=vesselId,proto3" json:"vessel_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *Consignment) Reset()         { *m = Consignment{} }
func (m *Consignment) String() string { return proto.CompactTextString(m) }
func (*Consignment) ProtoMessage()    {}
func (*Consignment) Descriptor() ([]byte, []int) {
	return fileDescriptor_e5e5ab05dfa973d5, []int{0}
}

func (m *Consignment) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Consignment.Unmarshal(m, b)
}
func (m *Consignment) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Consignment.Marshal(b, m, deterministic)
}
func (m *Consignment) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Consignment.Merge(m, src)
}
func (m *Consignment) XXX_Size() int {
	return xxx_messageInfo_Consignment.Size(m)
}
func (m *Consignment) XXX_DiscardUnknown() {
	xxx_messageInfo_Consignment.DiscardUnknown(m)
}

var xxx_messageInfo_Consignment proto.InternalMessageInfo

func (m *Consignment) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Consignment) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *Consignment) GetWeight() int32 {
	if m != nil {
		return m.Weight
	}
	return 0
}

func (m *Consignment) GetContainers() []*Container {
	if m != nil {
		return m.Containers
	}
	return nil
}

func (m *Consignment) GetVesselId() string {
	if m != nil {
		return m.VesselId
	}
	return ""
}

type Container struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	CustomerId           string   `protobuf:"bytes,2,opt,name=customer_id,json=customerId,proto3" json:"customer_id,omitempty"`
	Origin               string   `protobuf:"bytes,3,opt,name=origin,proto3" json:"origin,omitempty"`
	UserId               string   `protobuf:"bytes,4,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Container) Reset()         { *m = Container{} }
func (m *Container) String() string { return proto.CompactTextString(m) }
func (*Container) ProtoMessage()    {}
func (*Container) Descriptor() ([]byte, []int) {
	return fileDescriptor_e5e5ab05dfa973d5, []int{1}
}

func (m *Container) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Container.Unmarshal(m, b)
}
func (m *Container) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Container.Marshal(b, m, deterministic)
}
func (m *Container) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Container.Merge(m, src)
}
func (m *Container) XXX_Size() int {
	return xxx_messageInfo_Container.Size(m)
}
func (m *Container) XXX_DiscardUnknown() {
	xxx_messageInfo_Container.DiscardUnknown(m)
}

var xxx_messageInfo_Container proto.InternalMessageInfo

func (m *Container) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Container) GetCustomerId() string {
	if m != nil {
		return m.CustomerId
	}
	return ""
}

func (m *Container) GetOrigin() string {
	if m != nil {
		return m.Origin
	}
	return ""
}

func (m *Container) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

type Response struct {
	Created              bool         `protobuf:"varint,1,opt,name=created,proto3" json:"created,omitempty"`
	Consignment          *Consignment `protobuf:"bytes,2,opt,name=consignment,proto3" json:"consignment,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_e5e5ab05dfa973d5, []int{2}
}

func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (m *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(m, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetCreated() bool {
	if m != nil {
		return m.Created
	}
	return false
}

func (m *Response) GetConsignment() *Consignment {
	if m != nil {
		return m.Consignment
	}
	return nil
}

func init() {
	proto.RegisterType((*Consignment)(nil), "consignment.Consignment")
	proto.RegisterType((*Container)(nil), "consignment.Container")
	proto.RegisterType((*Response)(nil), "consignment.Response")
}

func init() {
	proto.RegisterFile("proto/consignment/consignment.proto", fileDescriptor_e5e5ab05dfa973d5)
}

var fileDescriptor_e5e5ab05dfa973d5 = []byte{
	// 295 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x51, 0x4f, 0x4b, 0x3b, 0x31,
	0x10, 0xfd, 0x6d, 0xff, 0xef, 0x04, 0x0a, 0xbf, 0x80, 0x35, 0xe8, 0xc1, 0x65, 0xbd, 0xf4, 0x54,
	0xa1, 0x82, 0x07, 0xaf, 0x05, 0xa1, 0xd7, 0xf4, 0xe2, 0x4d, 0x6b, 0x32, 0x6c, 0x07, 0x6c, 0xb2,
	0x24, 0x69, 0xfd, 0x52, 0x7e, 0x48, 0xd9, 0x6c, 0x57, 0xa3, 0xe2, 0x6d, 0xde, 0x7b, 0x33, 0xf3,
	0x5e, 0x32, 0x70, 0x5d, 0x3b, 0x1b, 0xec, 0x8d, 0xb2, 0xc6, 0x53, 0x65, 0xf6, 0x68, 0x42, 0x5a,
	0x2f, 0xa2, 0xca, 0x59, 0x42, 0x95, 0xef, 0x19, 0xb0, 0xd5, 0x17, 0xe6, 0x53, 0xe8, 0x91, 0x16,
	0x59, 0x91, 0xcd, 0x73, 0xd9, 0x23, 0xcd, 0x0b, 0x60, 0x1a, 0xbd, 0x72, 0x54, 0x07, 0xb2, 0x46,
	0xf4, 0xa2, 0x90, 0x52, 0x7c, 0x06, 0xa3, 0x37, 0xa4, 0x6a, 0x17, 0x44, 0xbf, 0xc8, 0xe6, 0x43,
	0x79, 0x42, 0xfc, 0x0e, 0x40, 0x59, 0x13, 0xb6, 0x64, 0xd0, 0x79, 0x31, 0x28, 0xfa, 0x73, 0xb6,
	0x9c, 0x2d, 0xd2, 0x38, 0xab, 0x4e, 0x96, 0x49, 0x27, 0xbf, 0x84, 0xfc, 0x88, 0xde, 0xe3, 0xeb,
	0x13, 0x69, 0x31, 0x8c, 0x7e, 0x93, 0x96, 0x58, 0xeb, 0x72, 0x0f, 0xf9, 0xe7, 0xd4, 0xaf, 0xac,
	0x57, 0xc0, 0xd4, 0xc1, 0x07, 0xbb, 0x47, 0xd7, 0xcc, 0xb6, 0x59, 0xa1, 0xa3, 0xd6, 0xba, 0x89,
	0x6a, 0x1d, 0x55, 0x64, 0x62, 0xd4, 0x5c, 0x9e, 0x10, 0x3f, 0x87, 0xf1, 0xc1, 0xb7, 0x43, 0x83,
	0x56, 0x68, 0xe0, 0x5a, 0x97, 0xcf, 0x30, 0x91, 0xe8, 0x6b, 0x6b, 0x3c, 0x72, 0x01, 0x63, 0xe5,
	0x70, 0x1b, 0xb0, 0xb5, 0x9c, 0xc8, 0x0e, 0xf2, 0x7b, 0x48, 0xbf, 0x34, 0xfa, 0xb2, 0xa5, 0xf8,
	0xf9, 0xd4, 0xae, 0x96, 0x69, 0xf3, 0xf2, 0x11, 0xa6, 0x9b, 0x1d, 0xd5, 0x64, 0xaa, 0x0d, 0xba,
	0x23, 0x29, 0xe4, 0x0f, 0xf0, 0x7f, 0x15, 0x17, 0xa7, 0x67, 0xf9, 0x73, 0xdb, 0xc5, 0xd9, 0x37,
	0xa5, 0x4b, 0x5b, 0xfe, 0x7b, 0x19, 0xc5, 0x6b, 0xdf, 0x7e, 0x04, 0x00, 0x00, 0xff, 0xff, 0x22,
	0x3c, 0x09, 0x6c, 0x14, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ShipingServiceClient is the client API for ShipingService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ShipingServiceClient interface {
	CreateConsignment(ctx context.Context, in *Consignment, opts ...grpc.CallOption) (*Response, error)
}

type shipingServiceClient struct {
	cc *grpc.ClientConn
}

func NewShipingServiceClient(cc *grpc.ClientConn) ShipingServiceClient {
	return &shipingServiceClient{cc}
}

func (c *shipingServiceClient) CreateConsignment(ctx context.Context, in *Consignment, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/consignment.ShipingService/CreateConsignment", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ShipingServiceServer is the server API for ShipingService service.
type ShipingServiceServer interface {
	CreateConsignment(context.Context, *Consignment) (*Response, error)
}

// UnimplementedShipingServiceServer can be embedded to have forward compatible implementations.
type UnimplementedShipingServiceServer struct {
}

func (*UnimplementedShipingServiceServer) CreateConsignment(ctx context.Context, req *Consignment) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateConsignment not implemented")
}

func RegisterShipingServiceServer(s *grpc.Server, srv ShipingServiceServer) {
	s.RegisterService(&_ShipingService_serviceDesc, srv)
}

func _ShipingService_CreateConsignment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Consignment)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShipingServiceServer).CreateConsignment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/consignment.ShipingService/CreateConsignment",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShipingServiceServer).CreateConsignment(ctx, req.(*Consignment))
	}
	return interceptor(ctx, in, info, handler)
}

var _ShipingService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "consignment.ShipingService",
	HandlerType: (*ShipingServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateConsignment",
			Handler:    _ShipingService_CreateConsignment_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/consignment/consignment.proto",
}
